<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Get Business Friendly Output</name>
  <uuid>0aebfb69-a8de-4a71-83d4-2a9078693c15</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[
	set decision to a new ML_Output where
		the prediction is the prediction of 'ML model invocation' , 
		the probabilities are the probabilities of 'ML model invocation' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
